#!/usr/bin/env bash

if [[ -s "/Users/meleeman/.rvm/environments/ruby-2.0.0-p0@railstutorial_rails_4_0" ]]
then
  source "/Users/meleeman/.rvm/environments/ruby-2.0.0-p0@railstutorial_rails_4_0"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/meleeman/.rvm/environments/ruby-2.0.0-p0@railstutorial_rails_4_0'" >&2
  exit 1
fi
